### PR TITLE
WIP: Convert to use termui

### PR DESCRIPTION
**Pull request by sedlund**
Wanted to run this by you to see if this is something you are interested in.

I am interested in converting to use the [termui](https://github.com/gizak/termui) library for use of its widgets to create a screen sort of like [PingPlotter](https://www.pingplotter.com/)

### CODE REVIEW

**Comment by tonobo** [comment]
Oh, awesome. The only reason why i have choosen goterm is to get a copyable output and of course its really easy

**Comment by tonobo** [comment]
I've applied the patch locally, looks quite well. :grin:

**Comment by sedlund** [comment]
Great!  I've been busy with other things so haven't gotten back to this yet.  If you are interested in this portion alone I can squash this and you can merge.   When I get more time I can look at the graphs

**Comment by tonobo** [comment]
no, keep calm ;) there is no need right now. :smile:

**Pull request closed without merging**
